apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: angular-app
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        name: angular-app
    spec:
      containers: 
        - image: nn-test-id
          name: client
          resources:
            limits:
              cpu: 1
              memory: 512M
            requests:
              cpu: 0.1
              memory: 256M}
      restartPolicy: Always
status: {}
